### PR TITLE
Allows use of complex expressions on Series

### PR DESCRIPTION
**Pull request by rhruiz**
With this you can define your series using (mix) configuration, such as

```
defmoule MyStat
  use Instream.Series

  database Application.get_env(:my_app, :database_name)
end
```

and push to different databases in different environments

### CODE REVIEW

**Comment by mneudert** [comment]
I see what you did there and like it.

After testing a bit on what the change actually accomplishes it might be worth to take this one a step further and make a bigger change at once.

Both the database and measurement are always stored and returned internally after a `to_string` conversion. That means there is actually no need for an atom. Leading to the conclusion the atom is sort of misplaced here and perhaps also "wrong" in the broadest sense. Like when using the database option of a connections `execute/2` there is a disparity in types between usage and definition. And that makes not that much sense if one takes a closer look at it :D

A backwards compatible deprecation of the atom is no problem and the new "pass anything that eventually becomes a `String.t`" would work just like your option as far as I have tested it.

What do you think about that?

**Comment by rhruiz** [comment]
Makes sense, influx does not know about atoms after all :)

**Comment by mneudert** [comment]
Could you take a look at the branch [series-string-definition](https://github.com/mneudert/instream/tree/series-string-definition)?

There is a complete switch of the series definition including a compile time deprecation notice. I probably went a bit overboard with [the tests](https://github.com/mneudert/instream/blob/series-string-definition/test/instream/series_test.exs#L73) but that is all the new fuzz working with your suggestion.

If it matches your needs I would merge it and release a new library version "soon". (Planned that for the next days anyways)

**Comment by rhruiz** [comment]
Works great for me :)

I will close this PR

thanks

**Pull request closed without merging**
